### ISSUE TITLE
mergeCavemanResults 

### ISSUE THREAD

**Issue by ramaniak** [ccmbioinfo/mugqic_pipelines#5]
Hello,
I did not find any documentation for this script in the main documentation page, but did run across it  when searching the repository. Is this script meant to be run after the estep to combine all the variant calls? 

I did try running it as follows:
```
mergeCavemanResults --output cavemen_muts_all_merge.vcf -s splitList -f results/*/*.muts.vcf
```
and get the following error
```
Option -f 10/101370875_102065298.muts.vcf doesn't match the required pattern. at ../mergeCavemanResults line 209.
	main::getDirsAndPattern("10/101370875_102065298.muts.vcf") called at ../mergeCavemanResults line 191
	main::setup() called at ../mergeCavemanResults line 50
```

Could you please let me know if this is meant to be run this way? If not, is there a tool you would recommend for combining the final variant calls?

thanks
Arun

**Comment by mike8115** [comment]
Hi Arun, this may be better addressed by the developers of CaVEMan. However, looking at the code in their repository, I can see where everything went wrong:

```perl
if($filepath =~ m/^(.+\/%)+\/(%.+){1}$/){
    $dir = $1;
    $files = $2;
}else{
    croak("Option -f $filepath doesn't match the required pattern.");
}
```

For some reason, the regex doesn't match * wildcards. It wants "%" where we normally put *. To pass this if test, your string should be `results/%/%.muts.vcf`. Afterwards, things should work. No idea why they did that. In fact, a few line down, they substituted '%' into *. Hope it helps!

**Comment by ramaniak** [comment]
I meant to have this on the caveman website. I did change that and it had an issue downstream. I will ask in their forum as well.
